name: Preview docs on fork

on:
  push:
    branches: [zensical]

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: macos-latest  # nicer screenshots
    if: github.repository == 'gselzer/scenex'
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Config git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git fetch origin gh-pages --depth=1 || true

      - name: Autogenerate examples
        run: |
          uv run python docs/gen_examples.py

      - name: Deploy dev docs
        run: uv run mike deploy --push --update-aliases zensical
        env:
          DOCS_DEV: true
          UV_PYTHON: "3.13"

      # - name: Update default release docs
      #   run: mike set-default --push latest
